//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenciaServicioTutorias
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeInicioSesion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class MensajeInicioSesion : object
    {
        
        private ReferenciaServicioTutorias.Academico academicoField;
        
        private bool errorField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Academico", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class Academico : object
    {
        
        private ReferenciaServicioTutorias.AcademicoRolAcademico[] AcademicoRolAcademicoField;
        
        private ReferenciaServicioTutorias.Estudiante[] EstudianteField;
        
        private ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativoField;
        
        private string contraseniaField;
        
        private string correoInstitucionalField;
        
        private string correoPersonalField;
        
        private int idAcademicoField;
        
        private System.Nullable<int> idProgramaEducativoField;
        
        private string nombreCompletoField;
        
        private string numPersonalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.AcademicoRolAcademico[] AcademicoRolAcademico
        {
            get
            {
                return this.AcademicoRolAcademicoField;
            }
            set
            {
                this.AcademicoRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Estudiante[] Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia
        {
            get
            {
                return this.contraseniaField;
            }
            set
            {
                this.contraseniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoPersonal
        {
            get
            {
                return this.correoPersonalField;
            }
            set
            {
                this.correoPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCompleto
        {
            get
            {
                return this.nombreCompletoField;
            }
            set
            {
                this.nombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numPersonal
        {
            get
            {
                return this.numPersonalField;
            }
            set
            {
                this.numPersonalField = value;
            }
        }

        public override string ToString()
        {
            return this.nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaEducativo", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ProgramaEducativo : object
    {
        
        private ReferenciaServicioTutorias.Academico[] AcademicoField;
        
        private ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoriaField;
        
        private int idProgramaEducativoField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Academico[] Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        public override string ToString()
        {
            return this.nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcademicoRolAcademico", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class AcademicoRolAcademico : object
    {
        
        private ReferenciaServicioTutorias.Academico AcademicoField;
        
        private ReferenciaServicioTutorias.RolAcademico RolAcademicoField;
        
        private System.Nullable<int> idAcademicoField;
        
        private int idAcademicoRolAcademicoField;
        
        private System.Nullable<int> idRolAcademicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.RolAcademico RolAcademico
        {
            get
            {
                return this.RolAcademicoField;
            }
            set
            {
                this.RolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcademicoRolAcademico
        {
            get
            {
                return this.idAcademicoRolAcademicoField;
            }
            set
            {
                this.idAcademicoRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idRolAcademico
        {
            get
            {
                return this.idRolAcademicoField;
            }
            set
            {
                this.idRolAcademicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class Estudiante : object
    {
        
        private ReferenciaServicioTutorias.Academico AcademicoField;
        
        private ReferenciaServicioTutorias.SesionTutoriaEstudiante[] SesionTutoriaEstudianteField;
        
        private string correoInstucionalField;
        
        private string correoPersonalField;
        
        private System.Nullable<int> idAcademicoField;
        
        private int idEstudianteField;
        
        private string matriculaField;
        
        private string nombreCompletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoriaEstudiante[] SesionTutoriaEstudiante
        {
            get
            {
                return this.SesionTutoriaEstudianteField;
            }
            set
            {
                this.SesionTutoriaEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstucional
        {
            get
            {
                return this.correoInstucionalField;
            }
            set
            {
                this.correoInstucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoPersonal
        {
            get
            {
                return this.correoPersonalField;
            }
            set
            {
                this.correoPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCompleto
        {
            get
            {
                return this.nombreCompletoField;
            }
            set
            {
                this.nombreCompletoField = value;
            }
        }

        public override string ToString()
        {
            return this.nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciaEducativa", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ExperienciaEducativa : object
    {
        
        private ReferenciaServicioTutorias.Academico AcademicoField;
        
        private ReferenciaServicioTutorias.PeriodoEscolar PeriodoEscolarField;
        
        private ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademicaField;
        
        private ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativoField;
        
        private System.Nullable<int> idAcademicoField;
        
        private int idEEField;
        
        private System.Nullable<int> idPeriodoEscolarField;
        
        private System.Nullable<int> idProgramaEducativoField;
        
        private string nombreField;
        
        private System.Nullable<int> nrcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.PeriodoEscolar PeriodoEscolar
        {
            get
            {
                return this.PeriodoEscolarField;
            }
            set
            {
                this.PeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademica
        {
            get
            {
                return this.ProblematicaAcademicaField;
            }
            set
            {
                this.ProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEE
        {
            get
            {
                return this.idEEField;
            }
            set
            {
                this.idEEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrc
        {
            get
            {
                return this.nrcField;
            }
            set
            {
                this.nrcField = value;
            }
        }

        public override string ToString()
        {
            return this.nrc.ToString() + " - " + this.nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolAcademico", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class RolAcademico : object
    {
        
        private ReferenciaServicioTutorias.AcademicoRolAcademico[] AcademicoRolAcademicoField;
        
        private System.Nullable<bool> esAdministradorField;
        
        private System.Nullable<bool> esCoordinadorField;
        
        private System.Nullable<bool> esJeFeCarreraField;
        
        private System.Nullable<bool> esTutorField;
        
        private int idRolAcademicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.AcademicoRolAcademico[] AcademicoRolAcademico
        {
            get
            {
                return this.AcademicoRolAcademicoField;
            }
            set
            {
                this.AcademicoRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esAdministrador
        {
            get
            {
                return this.esAdministradorField;
            }
            set
            {
                this.esAdministradorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esCoordinador
        {
            get
            {
                return this.esCoordinadorField;
            }
            set
            {
                this.esCoordinadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esJeFeCarrera
        {
            get
            {
                return this.esJeFeCarreraField;
            }
            set
            {
                this.esJeFeCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esTutor
        {
            get
            {
                return this.esTutorField;
            }
            set
            {
                this.esTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRolAcademico
        {
            get
            {
                return this.idRolAcademicoField;
            }
            set
            {
                this.idRolAcademicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesionTutoriaEstudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class SesionTutoriaEstudiante : object
    {
        
        private ReferenciaServicioTutorias.Estudiante EstudianteField;
        
        private ReferenciaServicioTutorias.SesionTutoria SesionTutoriaField;
        
        private System.Nullable<System.TimeSpan> horarioField;
        
        private System.Nullable<int> idEstudianteField;
        
        private System.Nullable<int> idSesionTutoriaField;
        
        private int idSesionTutoriaEstudianteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoria SesionTutoria
        {
            get
            {
                return this.SesionTutoriaField;
            }
            set
            {
                this.SesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> horario
        {
            get
            {
                return this.horarioField;
            }
            set
            {
                this.horarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSesionTutoria
        {
            get
            {
                return this.idSesionTutoriaField;
            }
            set
            {
                this.idSesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSesionTutoriaEstudiante
        {
            get
            {
                return this.idSesionTutoriaEstudianteField;
            }
            set
            {
                this.idSesionTutoriaEstudianteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesionTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class SesionTutoria : object
    {
        
        private ReferenciaServicioTutorias.ComentarioGeneral[] ComentarioGeneralField;
        
        private ReferenciaServicioTutorias.PeriodoEscolar PeriodoEscolarField;
        
        private ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoriaField;
        
        private ReferenciaServicioTutorias.SesionTutoriaEstudiante[] SesionTutoriaEstudianteField;
        
        private System.Nullable<System.DateTime> fechaLimiteField;
        
        private System.Nullable<System.DateTime> fechaSesionField;
        
        private System.Nullable<int> idPeriodoEscolarField;
        
        private int idSesionTutoriaField;
        
        private System.Nullable<int> numSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ComentarioGeneral[] ComentarioGeneral
        {
            get
            {
                return this.ComentarioGeneralField;
            }
            set
            {
                this.ComentarioGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.PeriodoEscolar PeriodoEscolar
        {
            get
            {
                return this.PeriodoEscolarField;
            }
            set
            {
                this.PeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoriaEstudiante[] SesionTutoriaEstudiante
        {
            get
            {
                return this.SesionTutoriaEstudianteField;
            }
            set
            {
                this.SesionTutoriaEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaLimite
        {
            get
            {
                return this.fechaLimiteField;
            }
            set
            {
                this.fechaLimiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaSesion
        {
            get
            {
                return this.fechaSesionField;
            }
            set
            {
                this.fechaSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSesionTutoria
        {
            get
            {
                return this.idSesionTutoriaField;
            }
            set
            {
                this.idSesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numSesion
        {
            get
            {
                return this.numSesionField;
            }
            set
            {
                this.numSesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolar", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class PeriodoEscolar : object
    {
        
        private ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativaField;
        
        private ReferenciaServicioTutorias.SesionTutoria[] SesionTutoriaField;
        
        private System.Nullable<System.DateTime> fechaFinField;
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private int idPeriodoEscolarField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ExperienciaEducativa[] ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoria[] SesionTutoria
        {
            get
            {
                return this.SesionTutoriaField;
            }
            set
            {
                this.SesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        public override string ToString()
        {
            return this.nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComentarioGeneral", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ComentarioGeneral : object
    {
        
        private ReferenciaServicioTutorias.SesionTutoria SesionTutoriaField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int idComentarioGeneralField;
        
        private System.Nullable<int> idSesionTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoria SesionTutoria
        {
            get
            {
                return this.SesionTutoriaField;
            }
            set
            {
                this.SesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComentarioGeneral
        {
            get
            {
                return this.idComentarioGeneralField;
            }
            set
            {
                this.idComentarioGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSesionTutoria
        {
            get
            {
                return this.idSesionTutoriaField;
            }
            set
            {
                this.idSesionTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ReporteTutoria : object
    {
        
        private ReferenciaServicioTutorias.ProblematicaAcademica ProblematicaAcademicaField;
        
        private ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativoField;
        
        private ReferenciaServicioTutorias.ReporteGeneral[] ReporteGeneralField;
        
        private ReferenciaServicioTutorias.SesionTutoria SesionTutoriaField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaEntregaField;
        
        private System.Nullable<int> idProblematicaAcademicaField;
        
        private System.Nullable<int> idProgramaEducativoField;
        
        private int idReporteTutoriaField;
        
        private System.Nullable<int> idSesionTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProblematicaAcademica ProblematicaAcademica
        {
            get
            {
                return this.ProblematicaAcademicaField;
            }
            set
            {
                this.ProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ReporteGeneral[] ReporteGeneral
        {
            get
            {
                return this.ReporteGeneralField;
            }
            set
            {
                this.ReporteGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SesionTutoria SesionTutoria
        {
            get
            {
                return this.SesionTutoriaField;
            }
            set
            {
                this.SesionTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProblematicaAcademica
        {
            get
            {
                return this.idProblematicaAcademicaField;
            }
            set
            {
                this.idProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProgramaEducativo
        {
            get
            {
                return this.idProgramaEducativoField;
            }
            set
            {
                this.idProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSesionTutoria
        {
            get
            {
                return this.idSesionTutoriaField;
            }
            set
            {
                this.idSesionTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicaAcademica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ProblematicaAcademica : object
    {
        
        private ReferenciaServicioTutorias.CategoriaProblematica CategoriaProblematicaField;
        
        private ReferenciaServicioTutorias.ExperienciaEducativa ExperienciaEducativaField;
        
        private ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoriaField;
        
        private ReferenciaServicioTutorias.SolucionProblematicaAcademica SolucionProblematicaAcademicaField;
        
        private ReferenciaServicioTutorias.SolucionProblematicaAcademica[] SolucionProblematicaAcademica1Field;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private System.Nullable<int> idCategoriaField;
        
        private System.Nullable<int> idEEField;
        
        private int idProblematicaACademicaField;
        
        private System.Nullable<int> idSolucionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.CategoriaProblematica CategoriaProblematica
        {
            get
            {
                return this.CategoriaProblematicaField;
            }
            set
            {
                this.CategoriaProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ExperienciaEducativa ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ReporteTutoria[] ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SolucionProblematicaAcademica SolucionProblematicaAcademica
        {
            get
            {
                return this.SolucionProblematicaAcademicaField;
            }
            set
            {
                this.SolucionProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.SolucionProblematicaAcademica[] SolucionProblematicaAcademica1
        {
            get
            {
                return this.SolucionProblematicaAcademica1Field;
            }
            set
            {
                this.SolucionProblematicaAcademica1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCategoria
        {
            get
            {
                return this.idCategoriaField;
            }
            set
            {
                this.idCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEE
        {
            get
            {
                return this.idEEField;
            }
            set
            {
                this.idEEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProblematicaACademica
        {
            get
            {
                return this.idProblematicaACademicaField;
            }
            set
            {
                this.idProblematicaACademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSolucion
        {
            get
            {
                return this.idSolucionField;
            }
            set
            {
                this.idSolucionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaProblematica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class CategoriaProblematica : object
    {
        
        private ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademicaField;
        
        private int idCategoriaField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademica
        {
            get
            {
                return this.ProblematicaAcademicaField;
            }
            set
            {
                this.ProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria
        {
            get
            {
                return this.idCategoriaField;
            }
            set
            {
                this.idCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        public override string ToString()
        {
            return this.nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolucionProblematicaAcademica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class SolucionProblematicaAcademica : object
    {
        
        private ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademicaField;
        
        private ReferenciaServicioTutorias.ProblematicaAcademica ProblematicaAcademica1Field;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private System.Nullable<int> idProblematicaAcademicaField;
        
        private int idSolucionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProblematicaAcademica[] ProblematicaAcademica
        {
            get
            {
                return this.ProblematicaAcademicaField;
            }
            set
            {
                this.ProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ProblematicaAcademica ProblematicaAcademica1
        {
            get
            {
                return this.ProblematicaAcademica1Field;
            }
            set
            {
                this.ProblematicaAcademica1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProblematicaAcademica
        {
            get
            {
                return this.idProblematicaAcademicaField;
            }
            set
            {
                this.idProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolucion
        {
            get
            {
                return this.idSolucionField;
            }
            set
            {
                this.idSolucionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteGeneral", Namespace="http://schemas.datacontract.org/2004/07/ServiciosTutorias.Modelo")]
    public partial class ReporteGeneral : object
    {
        
        private ReferenciaServicioTutorias.ReporteTutoria ReporteTutoriaField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int idReporteGeneralField;
        
        private System.Nullable<int> idReporteTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferenciaServicioTutorias.ReporteTutoria ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporteGeneral
        {
            get
            {
                return this.idReporteGeneralField;
            }
            set
            {
                this.idReporteGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicioTutorias.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iniciarSesion", ReplyAction="http://tempuri.org/IService1/iniciarSesionResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.MensajeInicioSesion> iniciarSesionAsync(string correoInstitucional, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerRolAcademico", ReplyAction="http://tempuri.org/IService1/obtenerRolAcademicoResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.AcademicoRolAcademico> obtenerRolAcademicoAsync(int idAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerIdSesionTutoriaPorFechaSesion", ReplyAction="http://tempuri.org/IService1/obtenerIdSesionTutoriaPorFechaSesionResponse")]
        System.Threading.Tasks.Task<int> obtenerIdSesionTutoriaPorFechaSesionAsync(System.DateTime fechaSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarComentarioGeneral", ReplyAction="http://tempuri.org/IService1/registrarComentarioGeneralResponse")]
        System.Threading.Tasks.Task<bool> registrarComentarioGeneralAsync(ReferenciaServicioTutorias.ComentarioGeneral comentarioGeneralNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarAcademico", ReplyAction="http://tempuri.org/IService1/registrarAcademicoResponse")]
        System.Threading.Tasks.Task<bool> registrarAcademicoAsync(ReferenciaServicioTutorias.Academico academicoNuevo, string rolAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarAcademicoRolAcademico", ReplyAction="http://tempuri.org/IService1/registrarAcademicoRolAcademicoResponse")]
        System.Threading.Tasks.Task<bool> registrarAcademicoRolAcademicoAsync(int idAcademicoNuevo, string rolAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerEstudiantesPorIdAcademico", ReplyAction="http://tempuri.org/IService1/obtenerEstudiantesPorIdAcademicoResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesPorIdAcademicoAsync(int idAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAcademicoPorId", ReplyAction="http://tempuri.org/IService1/obtenerAcademicoPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.Academico> obtenerAcademicoPorIdAsync(int idAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarProblematicaAcademica", ReplyAction="http://tempuri.org/IService1/registrarProblematicaAcademicaResponse")]
        System.Threading.Tasks.Task<bool> registrarProblematicaAcademicaAsync(ReferenciaServicioTutorias.ProblematicaAcademica problematicaAcademicaNueva, int idCategoriaProblematica, int idExperienciaEducativa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerCategoriasProblematicas", ReplyAction="http://tempuri.org/IService1/obtenerCategoriasProblematicasResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.CategoriaProblematica[]> obtenerCategoriasProblematicasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerExperienciasEducativasPorIdPeriodoEscolar", ReplyAction="http://tempuri.org/IService1/obtenerExperienciasEducativasPorIdPeriodoEscolarResp" +
            "onse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa[]> obtenerExperienciasEducativasPorIdPeriodoEscolarAsync(int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerCategoriaProblematicaPorId", ReplyAction="http://tempuri.org/IService1/obtenerCategoriaProblematicaPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.CategoriaProblematica> obtenerCategoriaProblematicaPorIdAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerExperienciaEducativaPorId", ReplyAction="http://tempuri.org/IService1/obtenerExperienciaEducativaPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa> obtenerExperienciaEducativaPorIdAsync(int idExperiencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerSesionTutoriaPorId", ReplyAction="http://tempuri.org/IService1/obtenerSesionTutoriaPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.SesionTutoria> obtenerSesionTutoriaPorIdAsync(int idSesionTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPeriodoEscolarPorId", ReplyAction="http://tempuri.org/IService1/obtenerPeriodoEscolarPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar> obtenerPeriodoEscolarPorIdAsync(int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarHorarioSesion", ReplyAction="http://tempuri.org/IService1/registrarHorarioSesionResponse")]
        System.Threading.Tasks.Task<bool> registrarHorarioSesionAsync(ReferenciaServicioTutorias.SesionTutoria sesionTutoria, ReferenciaServicioTutorias.Estudiante estudiante, System.DateTime fechaHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/horarioOcupado", ReplyAction="http://tempuri.org/IService1/horarioOcupadoResponse")]
        System.Threading.Tasks.Task<bool> horarioOcupadoAsync(int idSesionTutoria, System.TimeSpan hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estudianteConHorario", ReplyAction="http://tempuri.org/IService1/estudianteConHorarioResponse")]
        System.Threading.Tasks.Task<bool> estudianteConHorarioAsync(int idEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerProblematicasAcademicas", ReplyAction="http://tempuri.org/IService1/obtenerProblematicasAcademicasResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProblematicaAcademica[]> obtenerProblematicasAcademicasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarSolucionProblematicaAcademica", ReplyAction="http://tempuri.org/IService1/registrarSolucionProblematicaAcademicaResponse")]
        System.Threading.Tasks.Task<bool> registrarSolucionProblematicaAcademicaAsync(ReferenciaServicioTutorias.SolucionProblematicaAcademica solucionProblematicaAcademica, int idProblematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarSolucionAProblematica", ReplyAction="http://tempuri.org/IService1/agregarSolucionAProblematicaResponse")]
        System.Threading.Tasks.Task<bool> agregarSolucionAProblematicaAsync(int idProblematica, int idSolucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/problematicaConSolucion", ReplyAction="http://tempuri.org/IService1/problematicaConSolucionResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProblematicaAcademica> problematicaConSolucionAsync(int idProblematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarEstudiante", ReplyAction="http://tempuri.org/IService1/registrarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> registrarEstudianteAsync(ReferenciaServicioTutorias.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarExperienciaEducativa", ReplyAction="http://tempuri.org/IService1/registrarExperienciaEducativaResponse")]
        System.Threading.Tasks.Task<bool> registrarExperienciaEducativaAsync(ReferenciaServicioTutorias.ExperienciaEducativa experienciaEducativa, int idProgramaEducativo, int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarFechasSesionTutoria", ReplyAction="http://tempuri.org/IService1/registrarFechasSesionTutoriaResponse")]
        System.Threading.Tasks.Task<bool> registrarFechasSesionTutoriaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarFechasCierreParaEntrega", ReplyAction="http://tempuri.org/IService1/registrarFechasCierreParaEntregaResponse")]
        System.Threading.Tasks.Task<bool> registrarFechasCierreParaEntregaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int sesionTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarFechasCierreParaEntrega", ReplyAction="http://tempuri.org/IService1/modificarFechasCierreParaEntregaResponse")]
        System.Threading.Tasks.Task<bool> modificarFechasCierreParaEntregaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int sesionTutoriaEditar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerProgramasEducativosPorId", ReplyAction="http://tempuri.org/IService1/obtenerProgramasEducativosPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProgramaEducativo> obtenerProgramasEducativosPorIdAsync(int idProgramaEducativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerProgramasEducativos", ReplyAction="http://tempuri.org/IService1/obtenerProgramasEducativosResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProgramaEducativo[]> obtenerProgramasEducativosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPeriodosEscolaresPorId", ReplyAction="http://tempuri.org/IService1/obtenerPeriodosEscolaresPorIdResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar> obtenerPeriodosEscolaresPorIdAsync(int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPeriodosEscolares", ReplyAction="http://tempuri.org/IService1/obtenerPeriodosEscolaresResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar[]> obtenerPeriodosEscolaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerSesionTutoriaPorIdPeriodoEscolar", ReplyAction="http://tempuri.org/IService1/obtenerSesionTutoriaPorIdPeriodoEscolarResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.SesionTutoria[]> obtenerSesionTutoriaPorIdPeriodoEscolarAsync(int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerExperienciasEducativasPorIdProgramaEducativo", ReplyAction="http://tempuri.org/IService1/obtenerExperienciasEducativasPorIdProgramaEducativoR" +
            "esponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa[]> obtenerExperienciasEducativasPorIdProgramaEducativoAsync(int idProgramaEducativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerEstudiantesSinTutor", ReplyAction="http://tempuri.org/IService1/obtenerEstudiantesSinTutorResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesSinTutorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAcademicos", ReplyAction="http://tempuri.org/IService1/obtenerAcademicosResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.Academico[]> obtenerAcademicosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/asignarAcademicoAEstudiante", ReplyAction="http://tempuri.org/IService1/asignarAcademicoAEstudianteResponse")]
        System.Threading.Tasks.Task<bool> asignarAcademicoAEstudianteAsync(int idAcademico, int idEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerEstudiantesConTutor", ReplyAction="http://tempuri.org/IService1/obtenerEstudiantesConTutorResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesConTutorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarProgramaEducativo", ReplyAction="http://tempuri.org/IService1/registrarProgramaEducativoResponse")]
        System.Threading.Tasks.Task<bool> registrarProgramaEducativoAsync(ReferenciaServicioTutorias.ProgramaEducativo programaEducativoNuevo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ReferenciaServicioTutorias.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ReferenciaServicioTutorias.IService1>, ReferenciaServicioTutorias.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.MensajeInicioSesion> iniciarSesionAsync(string correoInstitucional, string contrasenia)
        {
            return base.Channel.iniciarSesionAsync(correoInstitucional, contrasenia);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.AcademicoRolAcademico> obtenerRolAcademicoAsync(int idAcademico)
        {
            return base.Channel.obtenerRolAcademicoAsync(idAcademico);
        }
        
        public System.Threading.Tasks.Task<int> obtenerIdSesionTutoriaPorFechaSesionAsync(System.DateTime fechaSesion)
        {
            return base.Channel.obtenerIdSesionTutoriaPorFechaSesionAsync(fechaSesion);
        }
        
        public System.Threading.Tasks.Task<bool> registrarComentarioGeneralAsync(ReferenciaServicioTutorias.ComentarioGeneral comentarioGeneralNuevo)
        {
            return base.Channel.registrarComentarioGeneralAsync(comentarioGeneralNuevo);
        }
        
        public System.Threading.Tasks.Task<bool> registrarAcademicoAsync(ReferenciaServicioTutorias.Academico academicoNuevo, string rolAcademico)
        {
            return base.Channel.registrarAcademicoAsync(academicoNuevo, rolAcademico);
        }
        
        public System.Threading.Tasks.Task<bool> registrarAcademicoRolAcademicoAsync(int idAcademicoNuevo, string rolAcademico)
        {
            return base.Channel.registrarAcademicoRolAcademicoAsync(idAcademicoNuevo, rolAcademico);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesPorIdAcademicoAsync(int idAcademico)
        {
            return base.Channel.obtenerEstudiantesPorIdAcademicoAsync(idAcademico);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.Academico> obtenerAcademicoPorIdAsync(int idAcademico)
        {
            return base.Channel.obtenerAcademicoPorIdAsync(idAcademico);
        }
        
        public System.Threading.Tasks.Task<bool> registrarProblematicaAcademicaAsync(ReferenciaServicioTutorias.ProblematicaAcademica problematicaAcademicaNueva, int idCategoriaProblematica, int idExperienciaEducativa)
        {
            return base.Channel.registrarProblematicaAcademicaAsync(problematicaAcademicaNueva, idCategoriaProblematica, idExperienciaEducativa);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.CategoriaProblematica[]> obtenerCategoriasProblematicasAsync()
        {
            return base.Channel.obtenerCategoriasProblematicasAsync();
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa[]> obtenerExperienciasEducativasPorIdPeriodoEscolarAsync(int idPeriodoEscolar)
        {
            return base.Channel.obtenerExperienciasEducativasPorIdPeriodoEscolarAsync(idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.CategoriaProblematica> obtenerCategoriaProblematicaPorIdAsync(int idCategoria)
        {
            return base.Channel.obtenerCategoriaProblematicaPorIdAsync(idCategoria);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa> obtenerExperienciaEducativaPorIdAsync(int idExperiencia)
        {
            return base.Channel.obtenerExperienciaEducativaPorIdAsync(idExperiencia);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.SesionTutoria> obtenerSesionTutoriaPorIdAsync(int idSesionTutoria)
        {
            return base.Channel.obtenerSesionTutoriaPorIdAsync(idSesionTutoria);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar> obtenerPeriodoEscolarPorIdAsync(int idPeriodoEscolar)
        {
            return base.Channel.obtenerPeriodoEscolarPorIdAsync(idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> registrarHorarioSesionAsync(ReferenciaServicioTutorias.SesionTutoria sesionTutoria, ReferenciaServicioTutorias.Estudiante estudiante, System.DateTime fechaHora)
        {
            return base.Channel.registrarHorarioSesionAsync(sesionTutoria, estudiante, fechaHora);
        }
        
        public System.Threading.Tasks.Task<bool> horarioOcupadoAsync(int idSesionTutoria, System.TimeSpan hora)
        {
            return base.Channel.horarioOcupadoAsync(idSesionTutoria, hora);
        }
        
        public System.Threading.Tasks.Task<bool> estudianteConHorarioAsync(int idEstudiante)
        {
            return base.Channel.estudianteConHorarioAsync(idEstudiante);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProblematicaAcademica[]> obtenerProblematicasAcademicasAsync()
        {
            return base.Channel.obtenerProblematicasAcademicasAsync();
        }
        
        public System.Threading.Tasks.Task<bool> registrarSolucionProblematicaAcademicaAsync(ReferenciaServicioTutorias.SolucionProblematicaAcademica solucionProblematicaAcademica, int idProblematica)
        {
            return base.Channel.registrarSolucionProblematicaAcademicaAsync(solucionProblematicaAcademica, idProblematica);
        }
        
        public System.Threading.Tasks.Task<bool> agregarSolucionAProblematicaAsync(int idProblematica, int idSolucion)
        {
            return base.Channel.agregarSolucionAProblematicaAsync(idProblematica, idSolucion);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProblematicaAcademica> problematicaConSolucionAsync(int idProblematica)
        {
            return base.Channel.problematicaConSolucionAsync(idProblematica);
        }
        
        public System.Threading.Tasks.Task<bool> registrarEstudianteAsync(ReferenciaServicioTutorias.Estudiante estudiante)
        {
            return base.Channel.registrarEstudianteAsync(estudiante);
        }
        
        public System.Threading.Tasks.Task<bool> registrarExperienciaEducativaAsync(ReferenciaServicioTutorias.ExperienciaEducativa experienciaEducativa, int idProgramaEducativo, int idPeriodoEscolar)
        {
            return base.Channel.registrarExperienciaEducativaAsync(experienciaEducativa, idProgramaEducativo, idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> registrarFechasSesionTutoriaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int idPeriodoEscolar)
        {
            return base.Channel.registrarFechasSesionTutoriaAsync(sesionesTutoria, idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> registrarFechasCierreParaEntregaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int sesionTutoria)
        {
            return base.Channel.registrarFechasCierreParaEntregaAsync(sesionesTutoria, sesionTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> modificarFechasCierreParaEntregaAsync(ReferenciaServicioTutorias.SesionTutoria[] sesionesTutoria, int sesionTutoriaEditar)
        {
            return base.Channel.modificarFechasCierreParaEntregaAsync(sesionesTutoria, sesionTutoriaEditar);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProgramaEducativo> obtenerProgramasEducativosPorIdAsync(int idProgramaEducativo)
        {
            return base.Channel.obtenerProgramasEducativosPorIdAsync(idProgramaEducativo);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ProgramaEducativo[]> obtenerProgramasEducativosAsync()
        {
            return base.Channel.obtenerProgramasEducativosAsync();
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar> obtenerPeriodosEscolaresPorIdAsync(int idPeriodoEscolar)
        {
            return base.Channel.obtenerPeriodosEscolaresPorIdAsync(idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.PeriodoEscolar[]> obtenerPeriodosEscolaresAsync()
        {
            return base.Channel.obtenerPeriodosEscolaresAsync();
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.SesionTutoria[]> obtenerSesionTutoriaPorIdPeriodoEscolarAsync(int idPeriodoEscolar)
        {
            return base.Channel.obtenerSesionTutoriaPorIdPeriodoEscolarAsync(idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.ExperienciaEducativa[]> obtenerExperienciasEducativasPorIdProgramaEducativoAsync(int idProgramaEducativo)
        {
            return base.Channel.obtenerExperienciasEducativasPorIdProgramaEducativoAsync(idProgramaEducativo);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesSinTutorAsync()
        {
            return base.Channel.obtenerEstudiantesSinTutorAsync();
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.Academico[]> obtenerAcademicosAsync()
        {
            return base.Channel.obtenerAcademicosAsync();
        }
        
        public System.Threading.Tasks.Task<bool> asignarAcademicoAEstudianteAsync(int idAcademico, int idEstudiante)
        {
            return base.Channel.asignarAcademicoAEstudianteAsync(idAcademico, idEstudiante);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioTutorias.Estudiante[]> obtenerEstudiantesConTutorAsync()
        {
            return base.Channel.obtenerEstudiantesConTutorAsync();
        }
        
        public System.Threading.Tasks.Task<bool> registrarProgramaEducativoAsync(ReferenciaServicioTutorias.ProgramaEducativo programaEducativoNuevo)
        {
            return base.Channel.registrarProgramaEducativoAsync(programaEducativoNuevo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54142/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
